version: '3.4'

services:
  app:
    image: app
    build:
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    # volumes:
    #   - .:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - MIX_HOME=/app/.mix
      # - MIX_ENV=dev
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
